spring:
   datasource:
      url: jdbc:mysql://localhost:3306/pet_store
      username: pet_store
      password: pet_store
      
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      defer-datasource-initialization: true
   
   sql:
      init:
         mode: always
         
logging:
   level:
      root: info
      pet_store: debug